name: web3js_test_page
version: 1.0.0+1

environment:
  sdk: ">=2.6.0-dev.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^1.2.1
  dartz: ^0.8.7
  modulovalue_project_widgets:
    git:
      url: git://github.com/modulovalue/modulovalue_project_widgets.git
      ref: 19d34e2be61bd27f57d4df979fcc1cb83779ee38
  decimal: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: any

flutter:
  uses-material-design: true
